import { RegisterRequestService } from '@src/_workspace/services/_request-registrer/RegisterRequestService'

export const RegisterRequestModel = {
    createRequest: async (dataItem: any) => RegisterRequestService.createRequest(dataItem),
    createDocument: async (dataItem: any) => RegisterRequestService.createDocument(dataItem),
    getAllRequests: async (dataItem?: any, sqlWhere: string = '') => RegisterRequestService.getAllRequests(dataItem, sqlWhere),
    getById: async (dataItem: any) => RegisterRequestService.getById(dataItem),
    updateStatus: async (dataItem: any) => RegisterRequestService.updateStatus(dataItem),
    updateRequest: async (dataItem: any) => RegisterRequestService.updateRequest(dataItem),
    sendAgreementEmail: async (dataItem: any) => RegisterRequestService.sendAgreementEmail(dataItem),
    getStatusOptions: async () => RegisterRequestService.getStatusOptions(),
    createApprovalStep: async (dataItem: any) => RegisterRequestService.createApprovalStep(dataItem),
    getApprovalSteps: async (dataItem: any) => RegisterRequestService.getApprovalSteps(dataItem),
    updateApprovalStep: async (dataItem: any) => RegisterRequestService.updateApprovalStep(dataItem),
    createApprovalLog: async (dataItem: any) => RegisterRequestService.createApprovalLog(dataItem),
    getApprovalLogs: async (dataItem: any) => RegisterRequestService.getApprovalLogs(dataItem),
    updateCcEmails: async (dataItem: any) => RegisterRequestService.updateCcEmails(dataItem),
    reassignAssignment: async (dataItem: any) => RegisterRequestService.reassignAssignment(dataItem),
    completeRegistration: async (dataItem: any) => RegisterRequestService.completeRegistration(dataItem),
    saveGprForm: async (dataItem: any) => RegisterRequestService.saveGprForm(dataItem),
    resolveEmployeeProfile: async (dataItem: any) => RegisterRequestService.resolveEmployeeProfile(dataItem),
    saveGprCNotification: async (dataItem: any) => RegisterRequestService.saveGprCNotification(dataItem),
    gprCGetFlow: async (dataItem: any) => RegisterRequestService.gprCGetFlow(dataItem),
    gprCSubmitSetup: async (dataItem: any) => RegisterRequestService.gprCSubmitSetup(dataItem),
    gprCApproveStep: async (dataItem: any) => RegisterRequestService.gprCApproveStep(dataItem),
    gprCRejectStep: async (dataItem: any) => RegisterRequestService.gprCRejectStep(dataItem),
    gprCActionRequired: async (dataItem: any) => RegisterRequestService.gprCActionRequired(dataItem),
    gprCRecordActionResult: async (dataItem: any) => RegisterRequestService.gprCRecordActionResult(dataItem),
    gprCQueue: async (dataItem: any) => RegisterRequestService.gprCQueue(dataItem),
    gprCTaskManagerQueue: async () => RegisterRequestService.gprCTaskManagerQueue(),
    gprCActionRequiredQueue: async (dataItem: any) => RegisterRequestService.gprCActionRequiredQueue(dataItem),
    getGprForm: async (request_id: number) => RegisterRequestService.getGprForm({ request_id }),
}
