export const BomPivotingSQL = {
  search: async (sqlWhere: string) => {
    return `
      SELECT
          tb_1.PRODUCT_CATEGORY_NAME AS PRODUCT_CATEGORY_NAME,
          tb_2.PRODUCT_MAIN_NAME AS PRODUCT_MAIN_NAME,
          tb_3.PRODUCT_SUB_NAME AS PRODUCT_SUB_NAME,
          tb_4.PRODUCT_TYPE_CODE_FOR_SCT AS PRODUCT_TYPE_CODE,
          tb_6.BOM_CODE AS BOM_CODE,
          tb_6.BOM_NAME AS BOM_NAME,
          tb_7.FLOW_CODE AS FLOW_CODE,
          tb_7.FLOW_NAME AS FLOW_NAME,
          tb_8.NO AS PROCESS_NO,
          tb_9.PROCESS_NAME AS PROCESS_NAME,
          tb_12.ITEM_CATEGORY_NAME AS ITEM_CATEGORY_NAME,
          tb_13.ITEM_CODE_FOR_SUPPORT_MES AS ITEM_CODE,
          tb_13.ITEM_EXTERNAL_FULL_NAME AS ITEM_NAME,
          tb_10.USAGE_QUANTITY AS USAGE_QTY,
          tb_14.SYMBOL AS UNIT
      FROM PRODUCT_CATEGORY tb_1
      INNER JOIN PRODUCT_MAIN tb_2
          ON tb_1.PRODUCT_CATEGORY_ID = tb_2.PRODUCT_CATEGORY_ID
      INNER JOIN PRODUCT_SUB tb_3
          ON tb_2.PRODUCT_MAIN_ID = tb_3.PRODUCT_MAIN_ID
      INNER JOIN PRODUCT_TYPE tb_4
          ON tb_3.PRODUCT_SUB_ID = tb_4.PRODUCT_SUB_ID
      INNER JOIN PRODUCT_TYPE_BOM tb_5
          ON tb_4.PRODUCT_TYPE_ID = tb_5.PRODUCT_TYPE_ID
      INNER JOIN BOM tb_6
          ON tb_5.BOM_ID = tb_6.BOM_ID
      INNER JOIN FLOW tb_7
          ON tb_6.FLOW_ID = tb_7.FLOW_ID
      INNER JOIN FLOW_PROCESS tb_8
          ON tb_7.FLOW_ID = tb_8.FLOW_ID
      INNER JOIN PROCESS tb_9
          ON tb_8.PROCESS_ID = tb_9.PROCESS_ID
      INNER JOIN BOM_FLOW_PROCESS_ITEM_USAGE tb_10
          ON tb_10.BOM_ID = tb_6.BOM_ID
          AND tb_10.FLOW_PROCESS_ID = tb_8.FLOW_PROCESS_ID
      INNER JOIN BOM_FLOW_PROCESS_ITEM_CHANGE_ITEM_CATEGORY tb_11
          ON tb_11.BOM_ID = tb_10.BOM_ID
          AND tb_11.FLOW_PROCESS_ID = tb_10.FLOW_PROCESS_ID
          AND tb_10.NO = tb_11.NO
      INNER JOIN ITEM_CATEGORY tb_12
          ON tb_11.ITEM_CATEGORY_ID = tb_12.ITEM_CATEGORY_ID
      INNER JOIN ITEM_MANUFACTURING tb_13
          ON tb_10.ITEM_ID = tb_13.ITEM_ID
      INNER JOIN UNIT_OF_MEASUREMENT tb_14
          ON tb_14.UNIT_OF_MEASUREMENT_ID = tb_13.USAGE_UNIT_ID
      WHERE tb_5.INUSE = 1
        AND tb_8.INUSE = 1
        AND tb_10.INUSE = 1
        ${sqlWhere}
      ORDER BY
          tb_1.PRODUCT_CATEGORY_NAME,
          tb_2.PRODUCT_MAIN_NAME,
          tb_3.PRODUCT_SUB_NAME,
          tb_4.PRODUCT_TYPE_CODE_FOR_SCT,
          tb_6.BOM_CODE,
          tb_8.NO,
          tb_12.ITEM_CATEGORY_NAME,
          tb_13.ITEM_CODE_FOR_SUPPORT_MES
    `
  },
}
