-- Workflow v2 logical-integrity audit (read-only).
-- Project convention: relate tables by IDs and JOINs, without physical FKs.

USE `vendor-system-test1`;

SELECT 'TARGET_CONTEXT' AS REPORT_SECTION,
       DATABASE() AS DATABASE_NAME,
       VERSION() AS MYSQL_VERSION,
       CURRENT_USER() AS AUTHENTICATED_ACCOUNT;

-- Expected result: zero rows.
SELECT 'UNEXPECTED_PHYSICAL_FOREIGN_KEYS' AS REPORT_SECTION,
       kcu.TABLE_NAME, kcu.CONSTRAINT_NAME, kcu.COLUMN_NAME,
       kcu.REFERENCED_TABLE_NAME, kcu.REFERENCED_COLUMN_NAME
FROM information_schema.KEY_COLUMN_USAGE kcu
WHERE kcu.CONSTRAINT_SCHEMA = DATABASE()
  AND kcu.REFERENCED_TABLE_NAME IS NOT NULL
  AND kcu.TABLE_NAME IN (
      'm_request_status', 'workflow_definition', 'workflow_step_master',
      'workflow_transition', 'request_register_vendor',
      'request_approval_step', 'request_approval_log'
  )
ORDER BY kcu.TABLE_NAME, kcu.CONSTRAINT_NAME, kcu.ORDINAL_POSITION;

-- IDs used by JOINs must remain indexed even though they are not FKs.
SELECT 'JOIN_INDEXES' AS REPORT_SECTION,
       TABLE_NAME, INDEX_NAME, NON_UNIQUE, SEQ_IN_INDEX, COLUMN_NAME
FROM information_schema.STATISTICS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME IN (
      'm_request_status', 'workflow_definition', 'workflow_step_master',
      'workflow_transition', 'request_register_vendor',
      'request_approval_step', 'request_approval_log'
  )
ORDER BY TABLE_NAME, INDEX_NAME, SEQ_IN_INDEX;

-- Every INVALID_ROWS value must be zero.
SELECT 'ORPHAN_WORKFLOW_STEP_DEFINITION' AS CHECK_NAME, COUNT(*) AS INVALID_ROWS
FROM workflow_step_master c LEFT JOIN workflow_definition p
  ON p.WORKFLOW_DEFINITION_ID = c.WORKFLOW_DEFINITION_ID
WHERE p.WORKFLOW_DEFINITION_ID IS NULL
UNION ALL
SELECT 'ORPHAN_WORKFLOW_STEP_STATUS', COUNT(*)
FROM workflow_step_master c LEFT JOIN m_request_status p
  ON p.M_REQUEST_STATUS_ID = c.M_REQUEST_STATUS_ID
WHERE p.M_REQUEST_STATUS_ID IS NULL
UNION ALL
SELECT 'ORPHAN_TRANSITION_DEFINITION', COUNT(*)
FROM workflow_transition c LEFT JOIN workflow_definition p
  ON p.WORKFLOW_DEFINITION_ID = c.WORKFLOW_DEFINITION_ID
WHERE p.WORKFLOW_DEFINITION_ID IS NULL
UNION ALL
SELECT 'ORPHAN_TRANSITION_FROM_STEP', COUNT(*)
FROM workflow_transition c LEFT JOIN workflow_step_master p
  ON p.WORKFLOW_STEP_MASTER_ID = c.FROM_WORKFLOW_STEP_MASTER_ID
WHERE p.WORKFLOW_STEP_MASTER_ID IS NULL
UNION ALL
SELECT 'ORPHAN_TRANSITION_TO_STEP', COUNT(*)
FROM workflow_transition c LEFT JOIN workflow_step_master p
  ON p.WORKFLOW_STEP_MASTER_ID = c.TO_WORKFLOW_STEP_MASTER_ID
WHERE c.TO_WORKFLOW_STEP_MASTER_ID IS NOT NULL
  AND p.WORKFLOW_STEP_MASTER_ID IS NULL
UNION ALL
SELECT 'ORPHAN_REQUEST_DEFINITION', COUNT(*)
FROM request_register_vendor c LEFT JOIN workflow_definition p
  ON p.WORKFLOW_DEFINITION_ID = c.WORKFLOW_DEFINITION_ID
WHERE p.WORKFLOW_DEFINITION_ID IS NULL
UNION ALL
SELECT 'ORPHAN_REQUEST_CURRENT_STATUS', COUNT(*)
FROM request_register_vendor c LEFT JOIN m_request_status p
  ON p.M_REQUEST_STATUS_ID = c.CURRENT_M_REQUEST_STATUS_ID
WHERE c.CURRENT_M_REQUEST_STATUS_ID IS NOT NULL
  AND p.M_REQUEST_STATUS_ID IS NULL;

SELECT 'ORPHAN_TASK_REQUEST' AS CHECK_NAME, COUNT(*) AS INVALID_ROWS
FROM request_approval_step c LEFT JOIN request_register_vendor p
  ON p.REQUEST_REGISTER_VENDOR_ID = c.REQUEST_REGISTER_VENDOR_ID
WHERE p.REQUEST_REGISTER_VENDOR_ID IS NULL
UNION ALL
SELECT 'ORPHAN_TASK_WORKFLOW_STEP', COUNT(*)
FROM request_approval_step c LEFT JOIN workflow_step_master p
  ON p.WORKFLOW_STEP_MASTER_ID = c.WORKFLOW_STEP_MASTER_ID
WHERE p.WORKFLOW_STEP_MASTER_ID IS NULL
UNION ALL
SELECT 'ORPHAN_EVENT_REQUEST_TASK_PAIR', COUNT(*)
FROM request_approval_log c LEFT JOIN request_approval_step p
  ON p.REQUEST_REGISTER_VENDOR_ID = c.REQUEST_REGISTER_VENDOR_ID
 AND p.REQUEST_APPROVAL_STEP_ID = c.REQUEST_APPROVAL_STEP_ID
WHERE p.REQUEST_APPROVAL_STEP_ID IS NULL
UNION ALL
SELECT 'ORPHAN_EVENT_WORKFLOW_STEP', COUNT(*)
FROM request_approval_log c LEFT JOIN workflow_step_master p
  ON p.WORKFLOW_STEP_MASTER_ID = c.WORKFLOW_STEP_MASTER_ID
WHERE p.WORKFLOW_STEP_MASTER_ID IS NULL
UNION ALL
SELECT 'ORPHAN_REQUEST_CURRENT_TASK_PAIR', COUNT(*)
FROM request_register_vendor c LEFT JOIN request_approval_step p
  ON p.REQUEST_REGISTER_VENDOR_ID = c.REQUEST_REGISTER_VENDOR_ID
 AND p.REQUEST_APPROVAL_STEP_ID = c.CURRENT_REQUEST_APPROVAL_STEP_ID
WHERE c.CURRENT_REQUEST_APPROVAL_STEP_ID IS NOT NULL
  AND p.REQUEST_APPROVAL_STEP_ID IS NULL;

SELECT 'DUPLICATE_REQUEST_STEP_ITERATION' AS REPORT_SECTION,
       REQUEST_REGISTER_VENDOR_ID, WORKFLOW_STEP_MASTER_ID,
       ITERATION_NO, COUNT(*) AS DUPLICATE_COUNT
FROM request_approval_step
GROUP BY REQUEST_REGISTER_VENDOR_ID, WORKFLOW_STEP_MASTER_ID, ITERATION_NO
HAVING COUNT(*) > 1;

SELECT 'MULTIPLE_ACTIVE_TASKS' AS REPORT_SECTION,
       REQUEST_REGISTER_VENDOR_ID, COUNT(*) AS ACTIVE_TASK_COUNT
FROM request_approval_step
WHERE INUSE = 1 AND LOWER(STEP_STATUS) = 'in_progress'
GROUP BY REQUEST_REGISTER_VENDOR_ID
HAVING COUNT(*) > 1;
